### ISSUE TITLE
HOWTO: uci set a service

### ISSUE THREAD

**Issue by poehlert** [gekmihesg/ansible-openwrt#14]
I'm trying to figure out what an ansible uci task entry would look to do the following command sequence. I've tried a bunch of different combinations but can't seem to get anything to work completely.

```
uci set ddns.foo=service
uci set ddns.foo.enabled=1
uci set ddns.foo.lookup_host=host
uci set ddns.foo.domain=domain
uci commit
```
expecting uci show ddns:
```
...
ddns.foo=service
ddns.foo.lookup_host='host'
ddns.foo.enabled='1'
ddns.foo.domain='domain'
```

Any help would be appreciated.

**Comment by gekmihesg** [comment]
```yaml
    - uci:
        command: "section"
        config: "ddns"
        type: "service"
        name: "foo"
        find_by:
          domain: "domain"
        value:
          lookup_host: "host"
          enabled: "1"
        replace: yes
```
This will use `domain` as "unique key" for ddns configs. If you have an ipv4 and an ipv6 config for the same domain, with everything else identical, you could do something like this:
```yaml
    - uci:
        command: "section"
        config: "ddns"
        type: "service"
        name: "foo"
        find_by:
          domain: "domain"
          use_ipv6: "{{ item }}"
        value:
          lookup_host: "host"
          enabled: "1"
        replace: yes
      loop: [0, 1]
```
