### ISSUE TITLE
ability to install multiple packages with opkg?

### ISSUE THREAD

**Issue by strowi** [gekmihesg/ansible-openwrt#22]
Hi,

thx for the work! As far is i could see, "opkg" can only install a single package at a time? 

E.g. the behaviour like the default "[package](https://docs.ansible.com/ansible/latest/modules/package_module.html)" isn't support, or am i wrong?

regards,
strowi

**Comment by gekmihesg** [comment]
You can install multiple packages by [separating package names by `,`](https://github.com/gekmihesg/ansible-openwrt/blob/master/library/openwrt_opkg.sh#L18). It is implemented like this to keep compatibility with the [upstream opkg module](https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/modules/packaging/os/opkg.py#L185). It still relies on the deprecated [squash actions](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-squash-actions) config. The opkg module never was part of the default list for that for some reason though. If you add it to your config you can use this to install multiple packages with a single module call (even though the syntax suggests to call the module once for each package):
```yaml
- opkg:
    name: "{{ item }}"
  loop:
  - foo
  - bar
```

Also, this should work for both module versions as well:
```yaml
- opkg:
    item: "{{ pkgs|join(',') }}"
  vars:
    pkgs:
    - foo
    - bar
```
