### ISSUE TITLE
get multiple sections

### ISSUE THREAD

**Issue by Grawp** [gekmihesg/ansible-openwrt#24]
Hello, Is there a possibility to get multiple sections of some type or matching some options so one can register the result into a variable so one can e.g. use the variable in the next task with some additional logic/filtering?

Simple use case: Delete all sections of type 'interface' from config 'network' except the one named 'loopback'.

Thanks

**Comment by gekmihesg** [comment]
Should now be possible doing something like this:
```yaml
- uci:
    command: find_all
    config: network
    type: interface
  register: all
- uci:
    command: find_all
    config: network
    type: interface
    find:
      ifname: lo
  register: loopback
- debug:
    var: all_but_loopback
  vars:
    all_but_loopback: "{{ all.result|difference(loopback.result) }}"
```
