### ISSUE TITLE
template not applying

### ISSUE THREAD

**Issue by JKDingwall** [gekmihesg/ansible-openwrt#30]
I have this task to apply a template:

```
- name: "Template system configuration file: /etc/config/network"
  template:
    src: "templates/etc/config/network.j2"
    dest: "/etc/config/network"
    mode: "0600"
    owner: root
    group: root
```

At the moment the template is just a plain file without any jinja2 macros.  Ansible always reports the file as changed but the file is never updated.

```
 ___________________________________________
/ TASK [Template system configuration file: \
\ /etc/config/network]                      /
 -------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [ap3] => {"changed": true}
```

```
$ apt-cache policy ansible
ansible:
  Installed: 2.9.17-1ppa~bionic
  Candidate: 2.9.17-1ppa~bionic
  Version table:
 *** 2.9.17-1ppa~bionic 500
        500 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.5.1+dfsg-1ubuntu0.1 500
        500 http://gb.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
     2.5.1+dfsg-1 500
        500 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

Using `--diff` correctly shows the expected changes to the file.

**Comment by JKDingwall** [comment]
Adding `-vvv` seems to show that openwrt_stat.sh is copied and executed presumably detecting the change base on a differing checksum of the template but the updated file is never transferred.  I see something similar trying to do a copy with this task:

```
- name: "Copy test"
  copy:
    src: "files/test"
    dest: "/tmp/test"
```
