### ISSUE TITLE
Struggling to use absent via key

### ISSUE THREAD

**Issue by AiyionPrime** [gekmihesg/ansible-openwrt#41]
First of all, thanks for this awesome piece of work, I just deployed my vlan config to my openwrt switches via ansible, and it's awesome :D

 One thing I'm struggling with is the `absent` function in the uci module though.
 
I've got a default section like this on my devices:
```uci
network.wan_vlan=bridge-vlan
network.wan_vlan.device='switch'
network.wan_vlan.vlan='1'
```

I could delete it by value as you did in your two examples:
```yaml
    - name: drop default bridge-vlan wan_vlan
      uci:
        command: absent
        config: network
        type: bridge-vlan
        find_by:
          vlan: 1
```

In case I ever wanted to use vlan one for something else, this would result in a non-idempotent mess.

I think I'm just using it wrong, but how would I correctly reference the option title `wan_vlan`?

I thought about this version (mimicing the syntax of section), which is apparently not right:

```yaml
- name: drop default bridge-vlan wan_vlan
      uci:
        command: absent
        config: network
        type: bridge-vlan
        name: wan_vlan
```

Thanks!

**Comment by AiyionPrime** [comment]
This appears to work:
```yaml
    - name: drop default bridge-vlan wan_vlan
      uci:
        command: absent
        type: bridge-vlan
        key: network.wan_vlan
```

**Comment by gekmihesg** [comment]
The `uci` module is a real mess. In this case, if you don't add a `find_by` key to your task, it just runs `uci -q delete $key` (see [here](https://github.com/gekmihesg/ansible-openwrt/blob/master/library/openwrt_uci.sh#L355)). All of these should work (not tested):
```yaml
    - name: drop default bridge-vlan wan_vlan
      uci:
        command: absent
        key: network.wan_vlan

    - name: drop default bridge-vlan wan_vlan
      uci:
        command: absent
        config: network
        section: wan_vlan

    - name: drop default bridge-vlan wan_vlan
      uci:
        command: delete
        key: network.wan_vlan
      failed_when: false
```
`find_by` can be useful for `absent`, if you have multiple sections of the same type but random or no names on them and you want to delete only one of those sections that has an `option foo 'bar'`.
