### ISSUE TITLE
uci add and add_list commands issue

### ISSUE THREAD

**Issue by itdoginfo** [gekmihesg/ansible-openwrt#6]
I encountered several errors when configuring with uci

1 playbook, add wireguard interface:
```
- name: add WG interface
  uci:
    command: add
    type: network
    key: network.wg0
```
 
```
TASK [add WG interface] **********************************************************************************************************************
fatal: [192.168.10.10]: FAILED! => {"changed": false, "command": "add", "config": "network", "msg": "uci add network.wg0 network: /sbin/uci: Entry not found", "result": "/sbin/uci: Entry not found", "section": "wg0"}
```

I think there is a issue with the command line syntax. Must be _uci add network network.wg0_

2 playbook, configuring wireguard interface. add_list command:
```
- name: add list
  uci:
    command: add_list
    key: network.wg0
    value:
      addresses: "192.168.1.2/24"
```
      
```
TASK [add list] ******************************************************************************************************************************
fatal: [192.168.10.10]: FAILED! => {"changed": false, "command": "add_list", "config": "network", "msg": "key and value required for add_list", "section": "wg0"}
```

I do this after setting up the interface. The command _uci add_list network.wg0.addresses=192.168.1.2/24_ is processed without errors.
Did I specify both parameters correctly? 

OpenWrt release 18.06.1

**Comment by gekmihesg** [comment]
I have to admit, the uci module is rather complicated.
Not sure how wireguard interfaces have to be configured, but let's assume they should look something like this:
```
# /etc/config/network

config interface 'mywg'
	option ifname 'wg0'
	option proto 'wireguard'
	list addresses '192.168.1.2/24'
```

Problem for your `command: add` is the `key` parameter. Whenever unsure how it has to look, just split it up into it's components. To generate the configuration above, there are multiple ways:
```yaml
# line by line:
    - uci:
        command: add
        config: network
        type: interface
        name: mywg
    - uci:
        command: set
        key: network.mywg.ifname
        value: wg0
    - uci:
        command: set
        key: network.mywg.proto
        value: wireguard
    - uci:
        command: add_list
        key: network.mywg.addresses
        value: 192.168.1.2/24

# all options at once
    - uci:
        command: add
        config: network
        type: interface
        name: mywg
    - uci:
        command: set
        key: network.mywg
        value:
          ifname: wg0
          proto: wireguard
          addresses:
            - 192.168.1.2/24

# whole section at once... well, this actually...
# - searches a section mywg of type interface
# - if not found, search a section of type interface with ifname=wg0 and rename it to mywg
# - if not found, create the section and set to contents to find_by
# - complete the contents of the section with value in all cases
    - uci:
        command: section
        config: network
        name: mywg
        type: interface
        find_by:
          ifname: wg0
        value:
          proto: wireguard
          addresses:
            - 192.168.1.2/24
```
The last one sounds complicated but is normally what I want to do and apart from `commit` the only command in my playbooks.

To make things easier (or maybe worse), I've added 4eda6e5915669d9f4357eb098484aa3c07e67761. This allows multiple ways to create a new section (applies to `command: add` and `command: section`).
```yaml
# these all do the same:
    - uci:
        command: add
        key: network.interface
        name: mywg
    - uci:
        command: add
        key: network.mywg
        type: interface
    - uci:
        command: add
        key: network.IGNORED
        name: mywg
        type: interface

# this creates a unnamed section of type interface:
    - uci:
        command: add
        key: network.interface
```

Hope that helps!

**Comment by itdoginfo** [comment]
Many thanks for the clarifications and examples!
One more question regarding item _type_.

We have the following wg client configuration:
```
config wireguard_wg0
	option public_key 'key'
etc
```
  
Through the uci we create it like this:
```
uci add network wireguard_wg0
uci set network.@wireguard_wg0[-1].public_key="key"
etc
```

Guess it should look something like this:
```
- name: add wireguard client config 
  uci:
    command: add
    config: network
    name: wireguard_wg0 
```

but 
```
TASK [add wireguard config] ******************************************************************************************************************
fatal: [192.168.10.10]: FAILED! => {"changed": false, "command": "add", "config": "network", "msg": "type required for add"}
```
 
 This is not a whim a wireguard. Examples from the default openwrt config /etc/config/network:
```
 config switch
        option name 'switch0'
        option reset '1'
        option enable_vlan '1'

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '0 8t'
```
Perhaps we can somehow forcibly ignore it? I tried to _type: IGNORED_ and was regarded as a type.
