### ISSUE TITLE
Feature Request: opkg: support upgrading all packages

### ISSUE THREAD

**Issue by wberrier** [gekmihesg/ansible-openwrt#62]
For example, with the `yum` module:

```yaml
yum:                                                                                                                                                                                                                                     
  name: '*'                                                                                                                                                                                                                              
  state: latest                                                                                                                                                                                                                          
```

It would be nice to be able to do the same with `opkg`:

```yaml
opkg:                                                                                                                                                                                                                                     
  name: '*'                                                                                                                                                                                                                              
  state: latest                                                                                                                                                                                                                          
```

Looking at the code, probably wouldn't be too bad to special case `*`, do `opkg list-upgradable` and feed that into `install_packages`.
